image: tmaier/docker-compose:19.03
services:
  - docker:19.03-dind

before_script:
  - docker version
  - docker-compose version

after_script:
  - docker images

stages:
  - lint
  - test
  - deploy

lint:
  stage: lint
  image: python:3.8
  before_script:
    - pip install pre-commit
  script:
    - pre-commit run -av

test-python-3.6:
  stage: test
  variables:
    PY_VERSION: "3.6"
  script:
    - docker-compose run tests

test-python-3.7:
  stage: test
  variables:
    PY_VERSION: "3.7"
  script:
    - docker-compose run tests

test-python-3.8:
  stage: test
  variables:
    PY_VERSION: "3.8"
  script:
    - docker-compose run tests

deploy:pypi:
  stage: deploy
  image: python:3.8
  before_script:
    - pip install poetry
  script:
    - poetry publish -u $PYPI_U -p $PYPI_P --build
  only:
    - releases
