version: '3.7'
services:
  tests:
    environment:
      CACHE_URL: redis://redis:6379/0
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - &img_tag aiohttp-cache:latest
    image: *img_tag
    volumes:
      - .:/aiohttp-cache
    depends_on:
      - redis
    command: pytest

  redis:
    image: "redis:5.0.7"
    ports:
      - "63790:6379"
